/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presupuesto;

import dao.PendientesObject;
import dao.PresupuestoDAO;
import dao.PresupuestoObject;
import dao.TipoPagoObject;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.joda.time.DateTime;


/**
 *
 * @author MaFuen1
 */
public class DetallePagosFinanciados extends javax.swing.JDialog {

    String[] columnNames = {"IDPAGO","PRESUPUESTO",
                        "CUOTA", "ESTADO","MONTO", "FEC PAGO MINIMO","FEC PAGO CONTADO"          
                        };
    String rowData[][]; 

    String path;
    PendientesObject obj;
    PresupuestoObject presupuesto;
    /**
     * Creates new form DetallePagosFinanciados
     */
    public DetallePagosFinanciados(java.awt.Frame parent, boolean modal,PendientesObject o,PresupuestoObject presupuesto,String p) {        
        super(parent, modal);
        initComponents();
        this.path=p;
        this.obj=o;
        this.presupuesto=presupuesto;
        setLocationRelativeTo(null);
        cargarPagos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_fechaCompra = new javax.swing.JLabel();
        lbl_plan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_tipo_pago = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_monto_total = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_pagado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_saldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagos realizados");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDPAGO", "MONTO", "FECHA"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_nombre.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        lbl_nombre.setText("Pendiente:");
        lbl_nombre.setToolTipText("");
        lbl_nombre.setRequestFocusEnabled(false);

        lbl_fechaCompra.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        lbl_fechaCompra.setText("Monto Cuota:");

        lbl_plan.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        lbl_plan.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel4.setText("Plan:");

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel5.setText("Fecha Compra:");

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel6.setText("Tipo de pago:");

        lbl_tipo_pago.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        lbl_tipo_pago.setText("jLabel7");

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel2.setText("Monto Total:");

        lbl_monto_total.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        lbl_monto_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_monto_total.setText("0.00");

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel3.setText("Pagado:");

        lbl_pagado.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        lbl_pagado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_pagado.setText("0.00");

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel1.setText("Saldo:");

        lbl_saldo.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        lbl_saldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_saldo.setText("0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_tipo_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_plan)
                                    .addComponent(lbl_fechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_pagado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_monto_total, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_plan)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(lbl_monto_total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fechaCompra)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(lbl_pagado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_tipo_pago)
                    .addComponent(jLabel1)
                    .addComponent(lbl_saldo)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
public void cargarPagos()
{
    try {
            // TODO add your handling code here:              
        PresupuestoDAO con = PresupuestoDAO.getInstance();                                   
        PendientesObject pendiente = con.getPendientes(this.obj.getIdentificador());        
          
        this.rowData=con.getFinanciadoPagos(pendiente.getIdentificador());
        actualizarTabla(this.rowData);       
                
        
        Utilities utils = new Utilities();
        
        lbl_nombre.setText(pendiente.getNombre());        
        lbl_monto_total.setText(utils.priceWithDecimal(Double.parseDouble(pendiente.getMonto_total())));      
        lbl_fechaCompra.setText(pendiente.getFecha());
        lbl_plan.setText( pendiente.getPlan());
        lbl_pagado.setText(utils.priceWithDecimal(Double.parseDouble(pendiente.getMonto_pagado()) ));
        lbl_tipo_pago.setText(pendiente.getTipo_pago());
        lbl_saldo.setText(utils.priceWithDecimal(Double.parseDouble(pendiente.getMonto_total())-Double.parseDouble(pendiente.getMonto_pagado())));

        
        /*Eliminado el 22/02/2016 no veo que haga nada.*/
        /*
            TipoPagoObject tipoPago = new TipoPagoObject(); 
            tipoPago = con.getTipoPago2(pendiente.getTipo_pago().toString());
            
            if (!tipoPago.getTipo_pago().equals("EFECTIVO"))
            {                
                String diaCorte = tipoPago.getFecha_corte();
                String diasPagoContado = tipoPago.getFecha_pago_contado();
                String diasPagoMinimo =  tipoPago.getFecha_pago_minimo();
                //SimpleDateFormat dateformat3 = new SimpleDateFormat("dd/MM/yyyy");
                //Date date_fechaCorte = dateformat3.parse(fechaCorte);
                               
            }     */   
   
    } catch (Exception ex) {
                DialogError error = new DialogError (null,true,ex);
               error.setVisible(true);
    }    
}


public void actualizarTabla (Object[][] datos){
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
         this.rowData,
         this.columnNames
    ){
       boolean[] canEdit = new boolean [] {
         false, false, false, false, false, false, false
     };
         @Override
         public boolean isCellEditable(int rowIndex, int columnIndex) {
             return canEdit[columnIndex];
         }   
 });

    jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
    jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
    jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_fechaCompra;
    private javax.swing.JLabel lbl_monto_total;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_pagado;
    private javax.swing.JLabel lbl_plan;
    private javax.swing.JLabel lbl_saldo;
    private javax.swing.JLabel lbl_tipo_pago;
    // End of variables declaration//GEN-END:variables
}
