/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presupuesto;

import dao.CuotaObject;
import dao.GastoObject;
import dao.PendientesObject;
import dao.PresupuestoDAO;
import dao.PresupuestoObject;
import dao.RubrosObject;
import dao.TipoPagoObject;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author MaFuen1
 */
public class JDialogListadoGastos extends javax.swing.JDialog {
    private final int INSERTAR = 1;
    private final int MODIFICAR = 2;
    
    String[] columnNames = {"IDGASTO","FECHA","RUBRO",
                        "LUGAR","TIPO PAGO","MONTO"           
                        };
    String rowData[][];    
    RubrosObject rubrosobject;
    String path;
    PresupuestoObject presupuesto;
    ImageIcon sumatoriaicon;
    String imgpath;
    /**
     * Creates new form JDialogListadoGastos
     */
    public JDialogListadoGastos(java.awt.Frame parent, boolean modal,String path,PresupuestoObject presupuesto) {
        super(parent, modal);
        initComponents();
        this.path=path;
        this.presupuesto=presupuesto;
        cargarGastos();
        setLocationRelativeTo(null);
         
        
        
        this.imgpath = System.getProperty("user.dir")+"\\";;        
        sumatoriaicon = new ImageIcon(getClass().getResource("/img/sumatoria.jpg"));
        btn_sumatoria.setIcon(sumatoriaicon);
    }


public void cargarGastos()
{
    try {
            // TODO add your handling code here:              
        PresupuestoDAO con = PresupuestoDAO.getInstance();                                           
         
        //Se elimina para evaluar si es necesario 11-02-2016
       // con.corregirGastos();
        
        this.rowData=con.getGastosxPresupuesto( Integer.parseInt(this.presupuesto.getIdpresupuesto()));
        actualizarTabla(this.rowData);       
                
        Utilities utils = new Utilities();
                
        if(rowData!=null){
            int registros = rowData.length;
            double tmp_monto,monto=0;
            for (int i=0; i<registros; i++)
            {                
                String str_monto = (String) rowData [i][5];
                
                try {                   
                    tmp_monto = Double.parseDouble(utils.priceWithoutCommas(str_monto));                    
                    monto = monto + tmp_monto;                                                            
                } catch (ParseException ex) {
                    ex.printStackTrace();
                }
                
             
            }        
        
        //Se elimina el llamado a la base de datos y se hace la sumatoria localmente 11/02/2016
        //double total = con.totalGastado(this.presupuesto.getIdpresupuesto());                
        
        lbl_total_gastado.setText(utils.priceWithDecimal(monto));
    }
   
    } catch (Exception ex) {
                DialogError error = new DialogError (null,true,ex);
               error.setVisible(true);
    }    
}


public void actualizarTabla (Object[][] datos){
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
         this.rowData,
         this.columnNames
    ){
       boolean[] canEdit = new boolean [] {
         false, false, false, false, false, false, false
     };
         @Override
         public boolean isCellEditable(int rowIndex, int columnIndex) {
             return canEdit[columnIndex];
         }   
 });

    jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
    jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
    jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_total_gastado = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_sumatoria = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            this.rowData,
            this.columnNames
        ));
        jScrollPane1.setViewportView(jTable1);

        lbl_total_gastado.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        lbl_total_gastado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_total_gastado.setText("0.00");
        lbl_total_gastado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel10.setText("Total de gastos:");

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gastos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_eliminar.setLabel("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_sumatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumatoriaActionPerformed(evt);
            }
        });

        jLabel2.setText("Listado de gasto realizados hasta este momento.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_sumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(30, 30, 30)
                        .addComponent(lbl_total_gastado, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(lbl_total_gastado))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_eliminar)
                        .addComponent(btn_modificar)
                        .addComponent(btn_sumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        try {
                Utilities utils = new Utilities();
                PresupuestoDAO con = PresupuestoDAO.getInstance();
                
                TableModel model = jTable1.getModel();
                
                int row = jTable1.getSelectedRow();
                int col = jTable1.getSelectedColumn();  
                
                if  (row!=-1 && col!=-1)
                {                                
                    String idgasto = model.getValueAt(row, 0).toString();
                    String nombre = model.getValueAt(row, 3).toString();
                    String monto = utils.priceWithoutCommas(model.getValueAt(row, 5).toString());
                    
                    this.rubrosobject =  con.getRubro2(idgasto);

                    if(JOptionPane.showConfirmDialog(null, "¿Desea eliminar el gasto '"+nombre+"'?",
                                                            "Warning",
                                                            JOptionPane.OK_CANCEL_OPTION,
                                                            JOptionPane.QUESTION_MESSAGE)
                                                            ==JOptionPane.OK_OPTION){                                                
                    
                    double saldo = Double.parseDouble(con.getSaldoRubro(Integer.parseInt(rubrosobject.getIdentificador())));              
                    double monto2 = Double.parseDouble(monto);

                    saldo = saldo + monto2;
                    con.modificarSaldoRubro(rubrosobject.getIdentificador(), String.valueOf(saldo));
                                                
                    con.borrarGasto(idgasto);
                                                            
                    CuotaObject cuota = new CuotaObject();
                    cuota.setIdrubro(this.rubrosobject.getIdentificador());
                    cuota.setFecha(utils.getDate());
                    cuota.setEstado(CuotaObject.ASIGNADO);
                    con.modificarEstadoCuota2(cuota);

                    int idfinanciado = con.getIdFinanciado(Integer.parseInt(this.rubrosobject.getIdentificador()));
                    
                    if (idfinanciado!=0){
                        double monto_pagado = con.getMontoPagado(idfinanciado);
                        double total =  monto_pagado - Double.parseDouble(monto);

                        con.modificarSaldodePendiente(idfinanciado,String.valueOf(total));
                        con.setPendienteACTIVO(String.valueOf(idfinanciado));
                    }
                    
                    cargarGastos();
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,
                    "Debe seleccionar un gasto de la tabla.");
                }                                    
            } catch (Exception ex) {
                DialogError error = new DialogError (null,true,ex);
                error.setVisible(true);
            }           
        
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
        Utilities utils = new Utilities ();
        TableModel model = jTable1.getModel();
        GastoObject obj = new GastoObject();

        int row = jTable1.getSelectedRow();
        int col = jTable1.getSelectedColumn();  

        if  (row!=-1 && col!=-1)
        {                                
            try {                                
                String idgasto = model.getValueAt(row, 0).toString();
                String fecha = model.getValueAt(row, 1).toString();
                String lugar = model.getValueAt(row, 3).toString();
                String tipo_pago = model.getValueAt(row, 4).toString();
                String monto = utils.priceWithoutCommas(model.getValueAt(row, 5).toString());
                
                PresupuestoDAO con = PresupuestoDAO.getInstance();
                this.rubrosobject =  con.getRubro2(idgasto);
                
                obj.setIdgasto(idgasto);
                obj.setFecha(fecha);
                obj.setLugar(lugar);
                obj.setTipo_pago(tipo_pago);
                obj.setMonto(monto);
                
                Gastos gastos = new Gastos (new JFrame(),true,this.MODIFICAR,rubrosobject,obj);
                gastos.setVisible(true);
                
                
                cargarGastos();
            }catch (ParseException ex) {
                               DialogError error = new DialogError (null,true,ex);         
                                error.setVisible(true);
                } catch (SQLException ex) {
                DialogError error = new DialogError (null,true,ex);         
                                error.setVisible(true);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,
            "Debe seleccionar un gasto de la tabla.");
        }         
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_sumatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumatoriaActionPerformed
        // TODO add your handling code here:
        
        btn_sumatoria();
        
    }//GEN-LAST:event_btn_sumatoriaActionPerformed

    public void btn_sumatoria(){
        TableModel model = jTable1.getModel();
        Utilities utils = new Utilities();
        
        int rowArr[] = jTable1.getSelectedRows();
        String monto="", saldo="";
        double sum_saldo=0, sum_monto=0, temp=0;
   
        
        for (int i=0; i<rowArr.length ; i++){
        
            if  (rowArr[i]!=-1)
            {                                
                try {
                    saldo = jTable1.getValueAt(rowArr[i], 5).toString();

                    saldo=utils.priceWithoutCommas(saldo);                                     
                    sum_saldo = sum_saldo + Double.parseDouble(saldo); 
                } catch (ParseException ex) {
                    DialogError error = new DialogError (null,true,ex);
                    error.setVisible(true);
                }

            }           
        }
        saldo = "Sumatoria: " +utils.priceWithDecimal(sum_saldo);
        
        JDialogsSumatorio s = new JDialogsSumatorio (null,true,monto,saldo);
        s.setVisible(true);
                
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_sumatoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_total_gastado;
    // End of variables declaration//GEN-END:variables
}
