/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presupuesto;

import dao.PresupuestoDAO;
import dao.RubroRecurrenteObject;
import dao.TiposPagoSingleton;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author MaFuen1
 */
public class JDialogRubrosRecurrentes extends javax.swing.JDialog {
    String path;
    RubroRecurrenteObject obj;
    boolean insertar=true;
    String tiposp[];
    
    /**
     * Creates new form JDialogRubrosRecurrentes
     */
    public JDialogRubrosRecurrentes(java.awt.Frame parent, boolean modal,String p) {
        super(parent, modal);
        initComponents();
        this.path=p;
        this.setTitle("Insertar Rubro");
        setLocationRelativeTo(null);
        insertar=true;

        PresupuestoDAO con;
        try {
            con = PresupuestoDAO.getInstance();
            TiposPagoSingleton tipospago_singleton = TiposPagoSingleton.getInstance();
            this.tiposp = tipospago_singleton.getTiposp();
            cmb_tipo_pago.setModel(new javax.swing.DefaultComboBoxModel(this.tiposp));
            cmb_tipo_pago.setSelectedItem("EFECTIVO");
        }catch(SQLException e){}        
    }
    
    public JDialogRubrosRecurrentes(java.awt.Frame parent, boolean modal,String p,RubroRecurrenteObject o) {
        super(parent, modal);
        initComponents();
        this.path=p;
        this.obj=o;
        this.setTitle("Modificar Rubro");
        setLocationRelativeTo(null);
        insertar=false;
        txt_nombre.setText(this.obj.getNombre());
        txt_monto.setText(this.obj.getMonto());
        cmb_quincena.setSelectedItem(this.obj.getQuincena());
        
        PresupuestoDAO con = null;
        try {
            con = PresupuestoDAO.getInstance();
            TiposPagoSingleton tipospago_singleton = TiposPagoSingleton.getInstance();
            this.tiposp = tipospago_singleton.getTiposp();
            cmb_tipo_pago.setModel(new javax.swing.DefaultComboBoxModel(this.tiposp));
            cmb_tipo_pago.setSelectedItem(this.obj.getTipo_pago());
        }catch(Exception ex){
                    DialogError error = new DialogError (null,true,ex);
                    error.setVisible(true);  
        }
        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_monto = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmb_quincena = new javax.swing.JComboBox();
        cmb_tipo_pago = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Monto:");

        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Quincena");

        cmb_quincena.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        jLabel4.setText("Tipo Pago");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmb_tipo_pago, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_quincena, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_monto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btn_aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cancelar)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_quincena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_tipo_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_cancelar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        if (this.insertar)
            insertarRubro();
        else
            modificarRubro();

    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

   public void insertarRubro()
   {
       try {
            if (txt_monto.getText().trim().equals("")|| txt_nombre.getText().trim().equals(""))
                JOptionPane.showMessageDialog(null,
                "Debe especificar todos los valores solicitados.");
       
            RubroRecurrenteObject obj = new RubroRecurrenteObject();
            obj.setEstado("ACTIVO");        
            obj.setNombre(txt_nombre.getText().trim());
            obj.setMonto(txt_monto.getText().trim());
            obj.setQuincena(cmb_quincena.getSelectedItem().toString());
            obj.setTipo_pago(cmb_tipo_pago.getSelectedItem().toString());

            PresupuestoDAO presupuestodao = null;
        
            presupuestodao = PresupuestoDAO.getInstance();
            presupuestodao.insertarRubroRecurrente(obj);
            
            this.setVisible(false);

        } catch (Exception ex) {
             DialogError error = new DialogError (null,true,ex);
               error.setVisible(true);
        }  
        
   
   }

   public void modificarRubro()
   {
       try { 
            if (txt_monto.getText().trim().equals("")|| txt_nombre.getText().trim().equals(""))
                    JOptionPane.showMessageDialog(null,
                    "Debe especificar todos los valores solicitados.");

            RubroRecurrenteObject o = new RubroRecurrenteObject();
            o.setEstado("ACTIVO");        
            o.setNombre(txt_nombre.getText().trim());
            o.setMonto(txt_monto.getText().trim());
            o.setQuincena(cmb_quincena.getSelectedItem().toString());
            o.setIdrubro(this.obj.getIdrubro());

            o.setTipo_pago(cmb_tipo_pago.getSelectedItem().toString());

            PresupuestoDAO presupuestodao = null;
        
            presupuestodao = PresupuestoDAO.getInstance();
            presupuestodao.modificarRubroRecurrente(o);
            
            this.setVisible(false);
            
        } catch (Exception ex) {
             DialogError error = new DialogError (null,true,ex);
               error.setVisible(true);
        }
        
   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JComboBox cmb_quincena;
    private javax.swing.JComboBox cmb_tipo_pago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_monto;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
