/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presupuesto;

import dao.ComprobanteObject;
import dao.DepositoObject;
import dao.PresupuestoDAO;
import dao.PresupuestoObject;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author MaFuen1
 */
public class JDialogDepositoComprobante extends javax.swing.JDialog {
PresupuestoObject presupuesto;
String tarjeta;

    /**
     * Creates new form JDialogDepositoComprobante
     */
    public JDialogDepositoComprobante(java.awt.Frame parent, boolean modal,PresupuestoObject pre,String tar) {
        super(parent, modal);
        initComponents();
        this.presupuesto=pre;
        this.tarjeta=tar;
     
        setLocationRelativeTo(null);
    }
    
    
    public JDialogDepositoComprobante(java.awt.Frame parent, boolean modal,PresupuestoObject pre,String tar, String ver) {
        super(parent, modal);
        initComponents();
        this.presupuesto=pre;
        this.tarjeta=tar;       
        
        txt_comprobante.setEditable(false);
        txt_lugar.setEditable(false);
        txt_fecha.setEditable(false);
        txt_monto.setEditable(false);
             
        setLocationRelativeTo(null);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_comprobante = new javax.swing.JTextField();
        txt_lugar = new javax.swing.JTextField();
        txt_fecha = new javax.swing.JTextField();
        txt_monto = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Comprobante");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Comprobante:");

        jLabel3.setText("Lugar:");

        jLabel4.setText("Fecha DD/MM/AAAA");

        jLabel5.setText("Monto:");

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_aceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_comprobante)
                        .addComponent(txt_lugar)
                        .addComponent(txt_fecha)
                        .addComponent(txt_monto, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
         agregarDeposito();
    }//GEN-LAST:event_btn_aceptarActionPerformed

    

    public void agregarDeposito(){
          try {                              
                Utilities utils = new Utilities ();
                PresupuestoDAO con = PresupuestoDAO.getInstance();
 
               if( con.hayxAsignar  (this.presupuesto.getIdpresupuesto(), tarjeta) )
               {
                JOptionPane.showMessageDialog(null,
                        "La tarjeta "+tarjeta+" tiene PAGADOS SIN ASIGNAR.");
               }
               else
               {
                    if (!con.depositoAplicado(this.presupuesto.getIdpresupuesto(), tarjeta))
                   {                    
                        
                       /*
                       En caso de que exista como un deposito pendiente se elimina.
                       */
                       con.borrarDepositoPendiente(this.presupuesto.getIdpresupuesto(), tarjeta);
                       
                       String comprobante = txt_comprobante.getText().trim();
                       String lugar = txt_lugar.getText().trim();
                       String fecha = txt_fecha.getText().trim();
                       String monto = txt_monto.getText().trim();                                                                                            
                       
                       
                        if ((comprobante != null) && (comprobante.length() > 0) &&
                              (lugar != null) && (lugar.length() > 0) &&  
                                (fecha != null) && (fecha.length() > 0) &&
                                (monto != null) && (monto.length() > 0) 
                                ) 
                        {
                            long iddeposito = con.getIDDEPOSITO_NEXTVAL();
                            DepositoObject deposito = new DepositoObject ();
                            
                            long idcomprobante = con.getIDCOMPROBANTE_NEXTVAL();

                            deposito.setIddeposito(String.valueOf(iddeposito));                    
                            deposito.setIdpresupuesto(this.presupuesto.getIdpresupuesto());
                            deposito.setIdusuario( con.getIdusuario_logueado());
                            deposito.setMonto(Double.parseDouble(monto));
                            deposito.setIdcomprobante(String.valueOf( idcomprobante));
                            deposito.setTipo_pago(tarjeta);
                            deposito.setEstado(DepositoObject.DEPOSITO_APLICADO);
                            deposito.setQuincena(this.presupuesto.getPresupuesto());

                            con.insertarDeposito(deposito);                              
                            
                            ComprobanteObject comobj = new ComprobanteObject();
                            comobj.setIdcomprobante(String.valueOf(idcomprobante));
                            comobj.setDocumento(comprobante);
                            comobj.setLugar(lugar);
                            comobj.setFecha(fecha);
                            comobj.setIdusuario(con.getIdusuario_logueado());
                            comobj.setMonto(Double.parseDouble(monto));
                            con.insertarComprobante(comobj);

                             con.insertarDepositoDetalleGastos (this.presupuesto.getIdpresupuesto(),String.valueOf(iddeposito),tarjeta) ;
                             con.insertarDepositoDetalleRubros (this.presupuesto.getIdpresupuesto(),String.valueOf(iddeposito),tarjeta) ;

                             
                                               JOptionPane.showMessageDialog(null,
                            "Deposito  Comprobante # "+comprobante+" registrado.");
                                               
                                               this.setVisible(false);

                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,
                            "Debe digitar un número, para poder registrar el depósito.");

                        }
                  }
                else
                   {
                       JOptionPane.showMessageDialog(null,
                       "La tarjeta ya tiene un deposito aplicado. Contacte al administrador.");

                   }                                                        
               }                                                            
             
            }catch (Exception ex) {
                DialogError error = new DialogError (null,true,ex);
                error.setVisible(true);
            }        
          
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txt_comprobante;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_lugar;
    private javax.swing.JTextField txt_monto;
    // End of variables declaration//GEN-END:variables
}
