/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presupuesto;

import dao.CuotaObject;
import dao.PresupuestoDAO;
import dao.PresupuestoObject;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author MaFuen1
 */
public class JDialogSalariosxQuincena extends javax.swing.JDialog {
    String[] columnNames = {"USUARIO","SALARIO","MOTIVO" 
                        };
    String rowData[][];    
    PresupuestoObject presupuesto;
    /**
     * Creates new form JDialogSalariosxQuincena
     */
    public JDialogSalariosxQuincena(java.awt.Frame parent, boolean modal,PresupuestoObject pre) {
        super(parent, modal);
        initComponents();
        
         this.presupuesto=pre;
        cargar();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_quincena = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbl_monto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_quincena.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        lbl_quincena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_quincena.setText("Salarios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_quincena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_quincena)
                .addContainerGap())
        );

        jLabel1.setText("Desgloce de salarios para la quincena actual.");
        jLabel1.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
        );

        jButton1.setLabel("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setLabel("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lbl_monto.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel3.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lbl_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_monto)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JDialogInsertarSalario s = new JDialogInsertarSalario (null,true,this.presupuesto);
        s.setVisible(true);
        cargar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      try {
                Utilities utils = new Utilities ();
                PresupuestoDAO con = PresupuestoDAO.getInstance();                                
                
                int rowArr[] = jTable1.getSelectedRows();
                
                if (rowArr.length ==0)        
                {
                JOptionPane.showMessageDialog(null,
                            "Debe seleccionar un rubro de la tabla.");
                }          
                
                for (int i=0; i<rowArr.length ; i++){
                if  (rowArr[i]!=-1)
                {                                
                    String salario = jTable1.getValueAt(rowArr[i], 1).toString();
                    String motivo = jTable1.getValueAt(rowArr[i], 2).toString();

                    if(JOptionPane.showConfirmDialog(null, "¿Desea eliminar el salario seleccionado?",
                                                            "Warning",
                                                            JOptionPane.OK_CANCEL_OPTION,
                                                            JOptionPane.QUESTION_MESSAGE)
                                                            ==JOptionPane.OK_OPTION){                                                
                       
                             salario = utils.priceWithoutCommas(salario);
                            con.borrarSalario(this.presupuesto.getIdpresupuesto(),motivo, Double.parseDouble(salario));
                           con.modificarMontoDisponible(this.presupuesto.getIdpresupuesto());     
                        
                    }
                }
                }                                                    
            } catch (Exception ex) {
                DialogError error = new DialogError (null,true,ex);
                error.setVisible(true);
            }     
            cargar();   
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void btn_modificar(){
        TableModel model = jTable1.getModel();
        Utilities utils = new Utilities();
        
        
        int row = jTable1.getSelectedRow();
        int col = jTable1.getSelectedColumn();  

        if  (row!=-1 && col!=-1)
        {                                
            try {
                String idusuario = jTable1.getValueAt(row, 0).toString();
                String salario = utils.priceWithoutCommas( jTable1.getValueAt(row, 1).toString());
                String motivo = jTable1.getValueAt(row, 2).toString();
                
                
                JDialogInsertarSalario s = new JDialogInsertarSalario (null,true,this.presupuesto,idusuario, salario,motivo);
                s.setVisible(true);
                cargar();
            } catch (ParseException ex) {
                Logger.getLogger(JDialogSalariosxQuincena.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,
            "Debe seleccionar un rubro de la tabla.");
        }     
    }
    

public void cargar()
{
    try {
            // TODO add your handling code here:              
        PresupuestoDAO con = PresupuestoDAO.getInstance();                                                            
        
        this.rowData=con.getSalariosQuincena(Integer.parseInt(this.presupuesto.getIdpresupuesto()));
        actualizarTabla(this.rowData);       
                
        Utilities utils = new Utilities();
                
        if(rowData!=null){
            int registros = rowData.length;
            double tmp_monto,monto=0;
            for (int i=0; i<registros; i++)
            {                
                String str_monto = (String) rowData [i][1];
                
                try {                   
                    tmp_monto = Double.parseDouble(utils.priceWithoutCommas(str_monto));                    
                    monto = monto + tmp_monto;                                                            
                } catch (ParseException ex) {
                    ex.printStackTrace();
                }                             
            } 
        
        lbl_monto.setText(utils.priceWithDecimal(monto));
    }
   
    } catch (Exception ex) {
                DialogError error = new DialogError (null,true,ex);
               error.setVisible(true);
    }    
}


public void actualizarTabla (Object[][] datos){
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
         this.rowData,
         this.columnNames
    ){
       boolean[] canEdit = new boolean [] {
         false, false, false, false, false, false, false
     };
         @Override
         public boolean isCellEditable(int rowIndex, int columnIndex) {
             return canEdit[columnIndex];
         }   
 });

    jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
    jTable1.getColumnModel().getColumn(1).setPreferredWidth(80);
    jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_monto;
    private javax.swing.JLabel lbl_quincena;
    // End of variables declaration//GEN-END:variables
}
