/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presupuesto;

import dao.PresupuestoDAO;
import dao.RubroRecurrenteObject;
import dao.TipoPagoObject;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author MaFuen1
 */
public class JDialogTipoPago extends javax.swing.JDialog {
    String path;
    
    TipoPagoObject tipo_pago_obj=null;
    Utilities utils = new Utilities();
    /**
     * Creates new form JDialogTipoPago
     */
    public JDialogTipoPago(java.awt.Frame parent, boolean modal,String p) {
        super(parent, modal);
        initComponents();
        this.path=p;
        setLocationRelativeTo(null); 
        
        
    }
    
    public JDialogTipoPago(java.awt.Frame parent, boolean modal,String p,TipoPagoObject tipo) {
        super(parent, modal);
        initComponents();
        this.path=p;
        this.tipo_pago_obj=tipo;
        setLocationRelativeTo(null); 
        
        PresupuestoDAO presupuestodao;
        try {
            presupuestodao = PresupuestoDAO.getInstance();
            this.tipo_pago_obj = presupuestodao.getTipoPago(tipo.getIdtipopago());

        } catch (Exception ex) {
             DialogError error = new DialogError (null,true,ex);
               error.setVisible(true);
        }                 
        
        txt_nombre_tipo_pago.setText(this.tipo_pago_obj.getTipo_pago());
        txt_fecha_corte.setText(this.tipo_pago_obj.getFecha_corte());
        txt_fecha_pago_minimo.setText(this.tipo_pago_obj.getFecha_pago_minimo());
        txt_fecha_pago_contado.setText(this.tipo_pago_obj.getFecha_pago_contado()); 
        cmb_tipo.setSelectedItem(this.tipo_pago_obj.getTipo());
                
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre_tipo_pago = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_fecha_corte = new javax.swing.JTextField();
        txt_fecha_pago_minimo = new javax.swing.JTextField();
        txt_fecha_pago_contado = new javax.swing.JTextField();
        cmb_tipo = new javax.swing.JComboBox();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipo de Pago");

        jLabel1.setText("Nombre del tipo de pago");

        jLabel2.setText("Día de corte");

        jLabel3.setText("Numero de días posteriores a la fecha de corte para hacer el Pago Mínimo");
        jLabel3.setToolTipText("");

        jLabel4.setText("Numero de días posteriores a la fecha de corte para hacer el Pago de Contado");

        jLabel5.setText("Tipo");

        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EFECTIVO", "DEBITO", "CREDITO" }));

        btn_aceptar.setLabel("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_aceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_cancelar))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_fecha_pago_minimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_fecha_pago_contado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_tipo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 336, Short.MAX_VALUE)
                                    .addComponent(txt_nombre_tipo_pago, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_fecha_corte)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nombre_tipo_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fecha_corte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(txt_fecha_pago_minimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txt_fecha_pago_contado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setAutoscrolls(true);

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel6.setText("Tipos de pago");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        if (this.tipo_pago_obj==null){
            insertarTipoPago();
        }
        else
        {
            modificarTipoPago();
        }
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed


    public void insertarTipoPago(){
        
        try {
            TipoPagoObject obj = new TipoPagoObject();

            String nombre=txt_nombre_tipo_pago.getText().trim();
            String fecha_corte=txt_fecha_corte.getText().trim();
            String fecha_pago_minimo=txt_fecha_pago_minimo.getText().trim();
            String fecha_pago_contado=txt_fecha_pago_contado.getText().trim();
            String tipo = cmb_tipo.getSelectedItem().toString();

            obj.setTipo_pago(nombre);
            obj.setFecha_corte(fecha_corte);
            obj.setFecha_pago_minimo(fecha_pago_minimo);
            obj.setFecha_pago_contado(fecha_pago_contado);
            obj.setTipo(tipo);


            PresupuestoDAO presupuestodao = null;
        
            presupuestodao = PresupuestoDAO.getInstance();
            presupuestodao.insertarTipoPago(obj);
            
            this.setVisible(false); 

        } catch (Exception ex) {
             DialogError error = new DialogError (null,true,ex);
               error.setVisible(true);
        }  
           
    }
    
    public void modificarTipoPago(){
        try {
            TipoPagoObject obj = new TipoPagoObject();

            String nombre=txt_nombre_tipo_pago.getText().trim();
            String fecha_corte=txt_fecha_corte.getText().trim();
            String fecha_pago_minimo=txt_fecha_pago_minimo.getText().trim();
            String fecha_pago_contado=txt_fecha_pago_contado.getText().trim();
            String tipo = cmb_tipo.getSelectedItem().toString();

            obj.setIdtipopago(this.tipo_pago_obj.getIdtipopago());
            obj.setTipo_pago(nombre);
            obj.setFecha_corte(fecha_corte);
            obj.setFecha_pago_minimo(fecha_pago_minimo);
            obj.setFecha_pago_contado(fecha_pago_contado);
            obj.setTipo(tipo);


            PresupuestoDAO presupuestodao = null;
        
            presupuestodao = PresupuestoDAO.getInstance();
            presupuestodao.modificarTipoPago(obj);
            this.setVisible(false);
        } catch (Exception ex) {
             DialogError error = new DialogError (null,true,ex);
               error.setVisible(true);
        }  
                 
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JComboBox cmb_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_fecha_corte;
    private javax.swing.JTextField txt_fecha_pago_contado;
    private javax.swing.JTextField txt_fecha_pago_minimo;
    private javax.swing.JTextField txt_nombre_tipo_pago;
    // End of variables declaration//GEN-END:variables
}
