/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presupuesto;

import dao.PresupuestoDAO;
import dao.UsuarioObject;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author MaFuen1
 */
public class JDialogUsuario extends javax.swing.JDialog {

        String idusuario=null;
        UsuarioObject usuario;
    /**
     * Creates new form JDialogUsuario
     */
    public JDialogUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
    }
    
    public JDialogUsuario(java.awt.Frame parent, boolean modal,String idusuario) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.idusuario=idusuario;
        cargar();
    }    

    

public void cargar()
{
    try {
            // TODO add your handling code here:              
        PresupuestoDAO con = PresupuestoDAO.getInstance();                                           
        Utilities utils = new Utilities();
        
        usuario=con.getUsuario(this.idusuario);
        
        txt_identificacion.setText(usuario.getIdUsuario());
        txt_nombre.setText(usuario.getNombre());
        txt_clave.setText(usuario.getClave());
        cmb_formapago.setSelectedItem(usuario.getPago());
        
        txt_quincena1.setText(String.valueOf(usuario.getQuincena1()));
        txt_quincena2.setText(String.valueOf(usuario.getQuincena2()));
        txt_mensual.setText(String.valueOf(usuario.getMensual()));
         cmb_perfil.setSelectedItem( usuario.getPerfil());
        
        
   
    } catch (Exception ex) {
                DialogError error = new DialogError (null,true,ex);
               error.setVisible(true);
    }    
}        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_window = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_identificacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        txt_quincena1 = new javax.swing.JTextField();
        txt_quincena2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmb_formapago = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txt_mensual = new javax.swing.JTextField();
        txt_clave = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmb_perfil = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_window.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        lbl_window.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_window.setText("Insertar Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_window, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_window)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Identificacion");

        jLabel2.setText("Nombre");

        jLabel3.setText("Clave");

        jLabel4.setText("Quincena 1");

        jLabel5.setText("Quincena 2");

        btn_aceptar.setLabel("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Forma de pago");

        cmb_formapago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Quincenal", "Mensual" }));

        jLabel7.setText("Mensual");

        jLabel8.setText("Perfil");

        cmb_perfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMINISTRADOR", "USUARIO" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_aceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelar))
                    .addComponent(txt_identificacion)
                    .addComponent(txt_nombre)
                    .addComponent(txt_quincena1)
                    .addComponent(txt_quincena2)
                    .addComponent(cmb_formapago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_mensual, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(txt_clave)
                    .addComponent(cmb_perfil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_formapago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_quincena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_quincena2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(cmb_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_cancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
           
        if (this.idusuario==null)
            insertar();
            else
            modificar();
        
    }//GEN-LAST:event_btn_aceptarActionPerformed

    
    public void insertar(){
    
      UsuarioObject usuario = new UsuarioObject();
        Utilities utils = new Utilities();
        
        usuario.setIdUsuario(txt_identificacion.getText().trim());
        usuario.setNombre(txt_nombre.getText().trim());
        
       
        
        usuario.setClave(txt_clave.getText().trim());
        usuario.setPago(cmb_formapago.getSelectedItem().toString());
        
        usuario.setQuincena1(Double.parseDouble(txt_quincena1.getText().trim()));
        usuario.setQuincena2(Double.parseDouble(txt_quincena2.getText().trim()));
        usuario.setMensual(Double.parseDouble(txt_mensual.getText().trim()));
        usuario.setPerfil(cmb_perfil.getSelectedItem().toString());

                PresupuestoDAO con;                                           
                  try {
                      con = PresupuestoDAO.getInstance();
                                            
                      con.insertarUsuario(usuario);

            JOptionPane.showMessageDialog(null,
            "Usuario insertado.");             
            this.setVisible(false);

                  } catch (SQLException ex) {
                DialogError error = new DialogError (null,true,ex);
               error.setVisible(true);
                  }
                             
    }
    
    
    public void modificar(){
      UsuarioObject usuario = new UsuarioObject();
        Utilities utils = new Utilities();
        
        usuario.setIdUsuario(txt_identificacion.getText().trim());
        usuario.setNombre(txt_nombre.getText().trim());
        
       
        
        usuario.setClave(txt_clave.getText().trim());
        usuario.setPago(cmb_formapago.getSelectedItem().toString());
        
        usuario.setQuincena1(  Double.parseDouble(txt_quincena1.getText().trim()));
        usuario.setQuincena2(Double.parseDouble(txt_quincena2.getText().trim()));
        usuario.setMensual(Double.parseDouble(txt_mensual.getText().trim()));
         usuario.setPerfil(cmb_perfil.getSelectedItem().toString());

                PresupuestoDAO con;                                           
                  try {
                      con = PresupuestoDAO.getInstance();
                                            
                      con.modificarUsuario(usuario);

            JOptionPane.showMessageDialog(null,
            "Usuario modificado.");          
            this.setVisible(false);

                  } catch (SQLException ex) {
                DialogError error = new DialogError (null,true,ex);
               error.setVisible(true);
                  }
                             
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JComboBox cmb_formapago;
    private javax.swing.JComboBox cmb_perfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_window;
    private javax.swing.JTextField txt_clave;
    private javax.swing.JTextField txt_identificacion;
    private javax.swing.JTextField txt_mensual;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_quincena1;
    private javax.swing.JTextField txt_quincena2;
    // End of variables declaration//GEN-END:variables
}
