/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presupuesto;

import dao.PendientesObject;
import dao.PresupuestoDAO;
import dao.PresupuestoObject;
import dao.RubroRecurrenteObject;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;

/**
 *
 * @author MaFuen1
 */
public class RubrosRecurrentes extends javax.swing.JDialog {
    String path;
    String[] columnNames = {"IDRUBRO","NOMBRE",
                        "MONTO","QUINCENA","TIPO PAGO"
                        };
    String rowData[][]; 
   
    
    CellEditorListener ChangeNotification = new CellEditorListener() {
        public void editingCanceled(ChangeEvent e) {
            System.out.println("The user canceled editing.");
        }

        public void editingStopped(ChangeEvent e) {
            System.out.println("The user stopped editing successfully.");
            modificar();
        }
    };    
    /**
     * Creates new form RubrosRecurrentes
     */
    public RubrosRecurrentes(java.awt.Frame parent, boolean modal,String p) {
        super(parent, modal);
        initComponents();
        this.path=p;
     
        cargar();
        setLocationRelativeTo(null);   
        
        jTable1.getDefaultEditor(String.class).addCellEditorListener(ChangeNotification);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_insertar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel1.setText("Listado de Rubros Recurrentes por quincena");
        jLabel1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_eliminar.setLabel("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_modificar.setLabel("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_insertar.setLabel("Insertar");
        btn_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_insertar)
                        .addGap(10, 10, 10)
                        .addComponent(btn_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_eliminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insertar)
                    .addComponent(btn_modificar)
                    .addComponent(btn_eliminar))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertarActionPerformed
        // TODO add your handling code here:

            JDialogRubrosRecurrentes insertar = new JDialogRubrosRecurrentes (new JFrame(),true,this.path);
            insertar.setVisible(true);
            cargar();       
    }//GEN-LAST:event_btn_insertarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
           try {
            PresupuestoDAO con = PresupuestoDAO.getInstance();

            TableModel model = jTable1.getModel();

            int row = jTable1.getSelectedRow();
            int col = jTable1.getSelectedColumn();  

            if  (row!=-1 && col!=-1)
            {                                
                String idrubro = model.getValueAt(row, 0).toString();
                String nombre = model.getValueAt(row, 1).toString();


                if(JOptionPane.showConfirmDialog(null, "¿Desea eliminar el rubro '"+nombre+"'?",
                                                        "Warning",
                                                        JOptionPane.OK_CANCEL_OPTION,
                                                        JOptionPane.QUESTION_MESSAGE)
                                                        ==JOptionPane.OK_OPTION){                                                
                    con.borrarRubroRecurrente(idrubro);
                    cargar();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,
                "Debe seleccionar un rubro de la tabla.");
            }


        } catch (Exception ex) {
            DialogError error = new DialogError (null,true,ex);
            error.setVisible(true);
        }         
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
          try {
            Utilities utils = new Utilities ();
            PresupuestoDAO con = PresupuestoDAO.getInstance();

            TableModel model = jTable1.getModel();

            int row = jTable1.getSelectedRow();
            int col = jTable1.getSelectedColumn();  

            if  (row!=-1 && col!=-1)
            {                                
                String idrubro = model.getValueAt(row, 0).toString();
                String nombre = model.getValueAt(row, 1).toString();
                String monto = utils.priceWithoutCommas(model.getValueAt(row, 2).toString());
                String quincena = model.getValueAt(row, 3).toString();
                String tipo_pago = model.getValueAt(row, 4).toString();
                
                RubroRecurrenteObject obj = new RubroRecurrenteObject();
                obj.setIdrubro(idrubro);
                obj.setNombre(nombre);
                obj.setMonto(monto);
                obj.setQuincena(quincena);
                obj.setTipo_pago(tipo_pago);
                
                JDialogRubrosRecurrentes modificar = new JDialogRubrosRecurrentes (new JFrame(),true,this.path,obj);
                modificar.setVisible(true);
                cargar();                

            }
            else
            {
                JOptionPane.showMessageDialog(null,
                "Debe seleccionar un rubro de la tabla.");
            }


        } catch (Exception ex) {
            DialogError error = new DialogError (null,true,ex);
            error.setVisible(true);
        }          
    }//GEN-LAST:event_btn_modificarActionPerformed


    public void cargar(){
    
        try {
            // TODO add your handling code here:
            PresupuestoDAO con = PresupuestoDAO.getInstance();            
            Object[][] datos =con.getRubrosRecurrentes();
            actualizarTabla(datos);
            
        }catch(Exception ex){
            DialogError error = new DialogError (null,true,ex);         
            error.setVisible(true);          
        }
  
    
    }
    

public void actualizarTabla(Object[][] datos){
   DefaultTableModel model;
   model = new javax.swing.table.DefaultTableModel(
           datos,
           this.columnNames
   )
   {
       final Class[] tiposColumnas = new Class[]{
                   java.lang.String.class,
                   java.lang.String.class,
                   java.lang.String.class,
                   java.lang.String.class,  
                   java.lang.String.class,
               };
       boolean[] canEdit = new boolean [] {
           false, true, true, false, false
       };
       Class[] tipos = tiposColumnas;

       @Override
       public boolean isCellEditable(int rowIndex, int columnIndex) {
           return canEdit [columnIndex];
       }
       @Override
       public Class getColumnClass(int columnIndex) {
           // Este método es invocado por el CellRenderer para saber que dibujar en la celda,
           // observen que estamos retornando la clase que definimos de antemano.
           return tipos[columnIndex];
       } 

   };
   
   jTable1.setModel(model);

   jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
   jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
   jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
   jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
}        
     

public void modificar(){
    try {
        Utilities utils = new Utilities();
        PresupuestoDAO con = PresupuestoDAO.getInstance();

        TableModel model = jTable1.getModel();

        int row = jTable1.getSelectedRow();
        int col = jTable1.getSelectedColumn();               
        if  (row!=-1 && col!=-1)
        {                      
            String idrubro = model.getValueAt(row, 0).toString();
            String nombre = model.getValueAt(row, 1).toString();
            String monto = utils.priceWithoutCommas(model.getValueAt(row, 2).toString());

            con.modificarRubroRecurrenteNOMBREYMONTO(nombre,monto,idrubro);

        }       

        cargar();                
    } catch (Exception ex) {
        DialogError error = new DialogError (null,true,ex);
        error.setVisible(true);
    }

}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_insertar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
