/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presupuesto;

import dao.PresupuestoDAO;
import dao.RubrosObject;
import dao.TiposPagoSingleton;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MaFuen1
 */
public class Rubros extends javax.swing.JDialog {
    int idpresupuesto;
    int quincena;
    int mes;
    int ano;
    String path;
    String tiposp[];
    RubrosObject rubro=null;
    boolean cancelar=false;
    /**
     * Creates new form Rubros
     */
    public Rubros(java.awt.Frame parent, boolean modal,int idpresupuesto,int quincena, int mes, int ano) {
        super(parent, modal);
        initComponents();
        this.idpresupuesto=idpresupuesto;
        this.quincena=quincena;
        this.mes=mes;
        String nmes="";
        this.ano=ano;        
        
       	
      setLocationRelativeTo(null);
      
       PresupuestoDAO con;
        try {
            con = PresupuestoDAO.getInstance();
            TiposPagoSingleton tipospago_singleton = TiposPagoSingleton.getInstance();
            this.tiposp = tipospago_singleton.getTiposp();
            
            cmb_tipo_pago.setModel(new javax.swing.DefaultComboBoxModel(this.tiposp));
            cmb_tipo_pago.setSelectedItem("EFECTIVO");
        }catch(SQLException e){}    

    }

    
    public Rubros(java.awt.Frame parent, boolean modal,String idrubro) {
        super(parent, modal);
        initComponents();
          
        setLocationRelativeTo(null);
      
       PresupuestoDAO con = null;
        try {
            con = PresupuestoDAO.getInstance();
            TiposPagoSingleton tipospago_singleton = TiposPagoSingleton.getInstance();
            this.tiposp = tipospago_singleton.getTiposp();
            
            
            cmb_tipo_pago.setModel(new javax.swing.DefaultComboBoxModel(this.tiposp));
            
            
            this.rubro = con.getRubro(idrubro);
            
            String tp = this.rubro.getTipo_pago();
            
            if (tp==null)
                cmb_tipo_pago.setSelectedItem("EFECTIVO");
            else                
                cmb_tipo_pago.setSelectedItem(this.rubro.getTipo_pago());
            
            
            txt_nombre.setText(this.rubro.getNombre());
            txt_monto.setText(this.rubro.getMonto());
          
          
            lbl_quincena.setText("Modificar Rubro");    
        
        }catch(SQLException e){}    

    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_monto = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmb_tipo_pago = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        lbl_quincena = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insertar Rubro al Presupuesto");

        jLabel2.setText("Rubro");

        jLabel3.setText("Monto");

        txt_monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_montoKeyReleased(evt);
            }
        });

        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Pagar a");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_monto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancelar))
                    .addComponent(txt_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_tipo_pago, 0, 262, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_tipo_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_cancelar))
                .addGap(27, 27, 27))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_quincena.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        lbl_quincena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_quincena.setText("Insertar Rubro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_quincena, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addGap(120, 120, 120))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lbl_quincena)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.cancelar=true;
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        if (this.rubro==null)
            insertarRubro();
        else
            modificarRubro();        
    }//GEN-LAST:event_btn_aceptarActionPerformed

    
    public void modificarRubro(){
    
       if ( txt_nombre.getText().trim().equals("")||txt_monto.getText().trim().equals(""))
        {
        JOptionPane.showMessageDialog(null,
                "Debe especificar todos los valores solicitados.");
        }
        else
        {
            PresupuestoDAO presupuestodao = null;
            try {
                presupuestodao = PresupuestoDAO.getInstance();
                
                this.rubro.setNombre(txt_nombre.getText().trim());
                this.rubro.setMonto(txt_monto.getText().trim()); 
                this.rubro.setTipo_pago(cmb_tipo_pago.getSelectedItem().toString());
                                
               // presupuestodao.modificarRubro(rubro);            
                
                double monto = Double.parseDouble(txt_monto.getText().trim());                
                presupuestodao.sp_modificar_rubro(this.rubro.getIdentificador(), txt_nombre.getText().trim(), monto, cmb_tipo_pago.getSelectedItem().toString());
                
                this.setVisible(false);
                
            } catch (Exception ex) {
                DialogError error = new DialogError (null,true,ex);
                error.setVisible(true);
            }          
        }
    }
    
    public void insertarRubro(){
    
       if ( txt_nombre.getText().trim().equals("")||txt_monto.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null,
                "Debe especificar todos los valores solicitados.");
        }
        else
        {
            PresupuestoDAO presupuestodao = null;
            try {
                presupuestodao = PresupuestoDAO.getInstance();
                
                RubrosObject rubro_tmp = new RubrosObject();
                rubro_tmp.setIdpresupuesto(String.valueOf(idpresupuesto));
                rubro_tmp.setNombre(txt_nombre.getText().trim());
                rubro_tmp.setMonto(txt_monto.getText().trim());
                rubro_tmp.setTipo_pago(cmb_tipo_pago.getSelectedItem().toString());                  
                
               // presupuestodao.insertarRubro(rubro_tmp);            
                
                double monto = Double.parseDouble(txt_monto.getText().trim());     
                presupuestodao.sp_insertar_rubro(String.valueOf(idpresupuesto), txt_nombre.getText().trim(), monto, cmb_tipo_pago.getSelectedItem().toString());
                
                this.setVisible(false);
                
            } catch (Exception ex) {
                 DialogError error = new DialogError (null,true,ex);
                 error.setVisible(true);
            }          
        }
    }
    
    private void txt_montoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_montoKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
             insertarRubro();
        }        
    }//GEN-LAST:event_txt_montoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JComboBox cmb_tipo_pago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_quincena;
    private javax.swing.JTextField txt_monto;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
