/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presupuesto;

import dao.PresupuestoDAO;
import dao.RubroRecurrenteObject;
import dao.TipoPagoObject;
import dao.TiposPagoSingleton;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author MaFuen1
 */
public class TiposPago extends javax.swing.JDialog {

    String path;
    String[] columnNames = {"IDTIPOPAGO","TIPO PAGO",
                        "TIPO"
                        };
    String rowData[][];     
    

    CellEditorListener ChangeNotification = new CellEditorListener() {
        public void editingCanceled(ChangeEvent e) {
            System.out.println("The user canceled editing.");
        }

        public void editingStopped(ChangeEvent e) {
            System.out.println("The user stopped editing successfully.");
            
        }
    };     
    /**
     * Creates new form TiposPago
     */
    public TiposPago(java.awt.Frame parent, boolean modal,String p) {
        super(parent, modal);
        initComponents();
        this.path=p;
        setLocationRelativeTo(null);  
        cargar();
        jTable1.getDefaultEditor(String.class).addCellEditorListener(ChangeNotification);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_insertar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipos de pago");

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel1.setText("Tipos de pago");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_insertar.setText("Insertar");
        btn_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertarActionPerformed(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_insertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insertar)
                    .addComponent(btn_modificar)
                    .addComponent(btn_eliminar))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertarActionPerformed
        // TODO add your handling code here:
        JDialogTipoPago tipos = new JDialogTipoPago(null,true,this.path);

        tipos.setVisible(true);  
                
        cargar();
    }//GEN-LAST:event_btn_insertarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
          try {
            Utilities utils = new Utilities ();
            PresupuestoDAO con = PresupuestoDAO.getInstance();

            TableModel model = jTable1.getModel();

            int row = jTable1.getSelectedRow();
            int col = jTable1.getSelectedColumn();  

            if  (row!=-1 && col!=-1)
            {                                
                String idtipopago = model.getValueAt(row, 0).toString();
                String nombre = model.getValueAt(row, 1).toString();
                String tipo = model.getValueAt(row, 2).toString();
                
                
                TipoPagoObject obj = new TipoPagoObject();
                obj.setIdtipopago(idtipopago);
                obj.setTipo_pago(nombre);
                obj.setTipo(tipo);

                
                JDialogTipoPago modificar = new JDialogTipoPago (new JFrame(),true,this.path,obj);
                modificar.setVisible(true);
                cargar();                

            }
            else
            {
                JOptionPane.showMessageDialog(null,
                "Debe seleccionar un Tipo de Pago de la tabla.");
            }


        } catch (Exception ex) {
            DialogError error = new DialogError (null,true,ex);
            error.setVisible(true);
        }          
         
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
         try {
            Utilities utils = new Utilities ();
            PresupuestoDAO con = PresupuestoDAO.getInstance();

            TableModel model = jTable1.getModel();

            int row = jTable1.getSelectedRow();
            int col = jTable1.getSelectedColumn();  

            if  (row!=-1 && col!=-1)
            {                                
                String idtipopago = model.getValueAt(row, 0).toString();

                con.borrarTipoPago(idtipopago);
                
                cargar();                
            }
            else
            {
                JOptionPane.showMessageDialog(null,
                "Debe seleccionar un Tipo de Pago de la tabla.");
            }

        } catch (Exception ex) {
            DialogError error = new DialogError (null,true,ex);
            error.setVisible(true);
        }          
                 
    }//GEN-LAST:event_btn_eliminarActionPerformed

   public void cargar(){
    
        try {
            // TODO add your handling code here:
            PresupuestoDAO con = PresupuestoDAO.getInstance();            
            Object[][] datos =con.getTiposPago();
            
            TiposPagoSingleton tp = TiposPagoSingleton.reload();
            
            actualizarTabla(datos);
            
        }catch(Exception ex){
            DialogError error = new DialogError (null,true,ex);         
            error.setVisible(true);          
        }
  
    
    }
    

public void actualizarTabla(Object[][] datos){
   DefaultTableModel model;
   model = new javax.swing.table.DefaultTableModel(
           datos,
           this.columnNames
   )
   {
       final Class[] tiposColumnas = new Class[]{
                   java.lang.String.class,
                   java.lang.String.class,
                   java.lang.String.class,                
               };
       boolean[] canEdit = new boolean [] {
           false, false, false,  
       };
       Class[] tipos = tiposColumnas;

       @Override
       public boolean isCellEditable(int rowIndex, int columnIndex) {
           return canEdit [columnIndex];
       }
       @Override
       public Class getColumnClass(int columnIndex) {
           // Este método es invocado por el CellRenderer para saber que dibujar en la celda,
           // observen que estamos retornando la clase que definimos de antemano.
           return tipos[columnIndex];
       } 

   };

   
   jTable1.setModel(model);


   jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
   jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
   jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);

}        
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_insertar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
